services:
  # Builds frontend
  frontend:
    build:
      context: .
      dockerfile: deployment/local/docker/build-front.Dockerfile
    container_name: frontend

    command:
      - sh
      - -c
      - |
          set -e

          npm run build &&

          rm -f /app/build/index.html &&
          cp /app/final/index.html /app/build/index.html &&

          mv /app/build/static/css/main.*.css /app/build/static/css/main.0293452a.css &&
          mv /app/build/static/css/main.*.css.map /app/build/static/css/main.0293452a.css.map && 
          mv /app/build/static/js/main.*.js /app/build/static/js/main.ccbf5c29.js &&
          mv /app/build/static/media/AppFont.*.woff2 /app/build/static/media/AppFont.31d6cfe0d16ae931b73c.woff2 &&

          # чистим final
          rm -rf /app/final/* &&

          # переносим всё из build в final
          cp -r /app/build/* /app/final/

    volumes:
      - ./build:/app/final
